import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import { SessionProvider } from "next-auth/react";
import Header from "@/components/molecules/Header";
import Footer from "@/components/molecules/Footer";
import Drawer from "@/components/molecules/Drawer";
import AuthSessionProvider from "@/providers/AuthSessionProvider";

import { Bakbak_One } from 'next/font/google'


const inter = Bakbak_One({
  weight:[ '400'],
  subsets:['devanagari'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthSessionProvider >
    <html lang="en">
      <body className={`${inter.className} `}>
        <Header />
        <Drawer/>
        {children}
      </body>
    </html>
    </AuthSessionProvider>
  );
}
