import type { Metadata } from "next";

import "./globals.css";

import Header from "@/components/molecules/Header";
import Footer from "@/components/molecules/Footer";

import AuthSessionProvider from "@/providers/AuthSessionProvider";

import { Bakbak_One } from 'next/font/google'


const inter = Bakbak_One({
  weight:[ '400'],
  subsets:['devanagari'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthSessionProvider >
    <html lang="en">
      <body className={`${inter.className} `}>
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
    </AuthSessionProvider>
  );
}
